# coding: utf-8

"""
    Fortune Cookie

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from fortune_cookie.apis.fortune_api import router as FortuneApiRouter

app = FastAPI(
    title="Fortune Cookie",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1.0",
)

app.include_router(FortuneApiRouter)
